version: "3.8"
services:
  wol-proxy:
    build: .
    environment:
      MAC_ADDRESS: "aa:bb:cc:dd:ee:ff"
      HEALTH_URL: "http://192.168.1.50/api/health"
      MAX_TIMEOUT: "45" # optional
    ports:
      - "8000:8000"
    restart: unless-stopped
